// nolint
package utils

import (
	"os"
	"testing"
)

func TestGetEnv(t *testing.T) {
	key := "TEST_ENV_VAR"
	val := "test_value"
	os.Setenv(key, val)    // nolint:errcheck
	defer os.Unsetenv(key) // nolint:errcheck

	if got := GetEnv(key, "fallback"); got != val {
		t.Errorf("GetEnv() = %v, want %v", got, val)
	}

	if got := GetEnv("NON_EXISTENT_VAR", "fallback"); got != "fallback" {
		t.Errorf("GetEnv() = %v, want %v", got, "fallback")
	}
}

func TestSecretBundleDecoder(t *testing.T) {
	// Real cluster secret bundle data which created and deleted already
	yamlData := `
cluster:
  id: YH3l-VgVZixkteeFT_sLGQL6xr3U00sA_VBkVTzoh5Q=
  secret: il5lLLFMQ1vJtWXDIB9CQpdl2DgTMdYytH0pD6KJcyM=
secrets:
  bootstraptoken: g4ywb6.g9g492ad01whv1s2
  secretboxencryptionsecret: 1BdsUedZXxCtFAzxtP9/6QRMhMxRSMB79sgGEw1bO1A=
trustdinfo:
  token: qysdpk.guqv58766fl63c52
certs:
  etcd:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmVENDQVNPZ0F3SUJBZ0lRZlo2U3RuOHpSbnhBZmkwcU5GM0RzREFLQmdncWhrak9QUVFEQWpBUE1RMHcKQ3dZRFZRUUtFd1JsZEdOa01CNFhEVEkxTVRJeE5ERTJNek15T1ZvWERUTTFNVEl4TWpFMk16TXlPVm93RHpFTgpNQXNHQTFVRUNoTUVaWFJqWkRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk5SaHZiZmdpaDRlCnZ4WGdtWmVMRkl3QnZKNGtlRi96RCs0Ti8zLy9Nc0NpOFJKY1dGbVFkbXRKb0dZNDgvajk5ZFpDdURObmdOOEcKMm1IeWZXRGRtKytqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjRApBUVlJS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVVUJNenczVmhSWWZMCjduZXQ5WU9PRXkrY1RHZ3dDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWdRR3QzQy83NkJZSE5zenNCRW11STByMWgKSG1jV3hLOFExRGtyK2IreWVkRUNJUURtVzFsV0NBcUJqblYwUjlkYlQxTHBORTYxMXkvbXlaWTZ6eU11NDdWNwpaQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUIvSElINlN6ZVRQSjBiUnI1Q3RlbGRFTEhJSzl4MExGYVl5ZzZ4V0Z4RWFvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFMUdHOXQrQ0tIaDYvRmVDWmw0c1VqQUc4bmlSNFgvTVA3ZzMvZi84eXdLTHhFbHhZV1pCMgphMG1nWmpqeitQMzExa0s0TTJlQTN3YmFZZko5WU4yYjd3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  k8s:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUpsQVI1SkJRUmlWRE51VnpBbThuSTh3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV5TVRReE5qTXpNamxhRncwek5URXlNVEl4TmpNegpNamxhTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVI5WkQxd1VrOE9PL2hSelc1aFNuWnc1M1VvMmRONFRjaEJYdXU0MWZpbkFIa2loSndPUDJOcDFHWlIKSEJrUEVCS3VydHJLdWt0bEgrcXowRjF2RlRMYW8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGRlhmSnhzTnRZL3ZoQml1L2t4N2xFSDBvaGNETUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSURMdVlnU2cKdmJCSGFDZE5BVVh3UjJXNzFZN3lZM1REMVlZYWJqbTNYTEpLQWlFQWtLT0U4N3Frb2JsVUJ5aEtwQkkyTlJCNwpHdEE0RWE0TDU4SDFCbFhqSHp3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUw5cENUeFpuWVhySmlKT1hoZ21DcGNJK2p3SUNQanlBWFlKQjRsTnlnQWlvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZldROWNGSlBEanY0VWMxdVlVcDJjT2QxS05uVGVFM0lRVjdydU5YNHB3QjVJb1NjRGo5agphZFJtVVJ3WkR4QVNycTdheXJwTFpSL3FzOUJkYnhVeTJnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  k8saggregator:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJYekNDQVFhZ0F3SUJBZ0lSQUtEV25JNlRmUC9NS2RLU1JSbDUvQkV3Q2dZSUtvWkl6ajBFQXdJd0FEQWUKRncweU5URXlNVFF4TmpNek1qbGFGdzB6TlRFeU1USXhOak16TWpsYU1BQXdXVEFUQmdjcWhrak9QUUlCQmdncQpoa2pPUFFNQkJ3TkNBQVRrSVF1WERxZVZzS1lPa0dNSVJOQWgwU3FkdVhIY2VuUTdiSStWTXpsUFZ3UzNHZ0NiCjJkUE1HOURDUzFxekZWbmQ0QlNKQU9ybGZHNjB5NXlCai9iOG8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXcKSFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpIUVlEVlIwT0JCWUVGRUMvOW5xN0lSR0FMbWlBY1B0MThzc1VxbE5mTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDCklBZGRwajh5WHNxWDA2Z0xuSDRrNlFuanh0bzFxeFBmd3pGQnlUMFQxRVMzQWlCYWo1ZGhCSENzMy9lc3BselkKaDdxNWVrTHV6bzh5SUdTL1k1dFpxSE83VkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUg5WGZnaXRTSWdia1U4ckNKYTJnNjlhSllEZ1ZqSGw0Q2RSWmgyaFNZaGJvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNUNFTGx3Nm5sYkNtRHBCakNFVFFJZEVxbmJseDNIcDBPMnlQbFRNNVQxY0V0eG9BbTluVAp6QnZRd2t0YXN4VlozZUFVaVFEcTVYeHV0TXVjZ1kvMi9BPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
  k8sserviceaccount:
    key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBek8xSklDTXVGeUF5NGIzVlRybml6QTBSQm5FcGhKbzR4T0hJVVhCOSs1cFowWGRpClVwSysyRlcrZ2lYNHZVYnhpU1JkYkw3N1VSaFZrcFZWdHBZS1c2L1M0cGhEVzVUVjFxeVQxMnl2MERXajQ0eEEKMXoyTzVJNDBiY3pLUVlnQ3lxTXNsdWR2R3lXMUt6bmw3cTc5dUFlMDV3Y3JHQVE5bFBwNFJRM0xtdHEzMnRSagp4VGtuUVBrQTUrZjA4SXFJaGdyWXd0MnFmTmY3YnRWRmgzdGhNcmZzQzBRWlN0N2pMVkFnRTl4d1JFQzZsNGthCnhmcTlRdmU0dTZYRklpT1lJcHpWa3lqdmlYYkhHM1V5Mk43amwxdk94MU5hVTJoYmlzTE93MHZaZ0lzVm9XR0YKenVvM3Y1aHBVNlVEVFVBclFUcmxXWTZ5dldQQmhiaHpnaGx5UmN4WGl4ak02WStPZlh2OG9kTDlUTlg5enBoaAo1RFJtclZQWGM1N24wT0lPVDRqLzB5M3dKOTAxN0t2YmFmNEJYeUZmRlF4UjV6eDVlWHhrUVZidXNwZmp6eGlzCmpGeXhSNFJUM0JOOFEzRjJzN3czdUJlc2RRRHJhZEYyZ2EyWE5PTkd4ZVhFcnRjd1I4M3cvRGw2ZnhDRDVOa1oKRHJ0c2dOMnVORmdja3dZNnRVNlpiWERBTm85MW9YYmNXb1FnU0RQNXNPb2JxSUgya1NZRjRrTnl0bTg3a3lqaApUTUluRzZIUUxnU3pHT1dDQnpEWUtsQndHREJlWlBIR29EK1p2R3NCNFZnbkY4MkZkbjdkQzliSUZMYnlQK3V6CnN6blA4OWhkODRyODFFeWZyR2RNcEhvbHpUdDZ1a1hocHVXSWhmR3hHdDlISHNjSTZ1L0cwdGRub0MwQ0F3RUEKQVFLQ0FnQUk2WlA1MWhYWjB5QnJZWEJ1dTFaaUJmcDAwNFNZL0FVV2lQUkhtSE1lTjIwTEYxeGJGMzg5MU9MVApjYmZTOFl3dEtQdjRNQWtwa251Y1E2cmw1VG9mbVRLOGdKOURVeUtHc3R3K0xQK3JlRDIvdG5pV2M5cXNWWVB4CnQ0dWZWSDA4bDJLbjBIcHNUWlJHeEQ2Y0JoZktRbW1MZDZ3WDRBMVdscHNXODcza1p2bENodVNzN2VxbllIejUKMlFSMTFxeVAyZFpxQ1M1eVBnbDFIVWpvRnNWWUtaZ1dPRmk2UVIzVHVXMmZ0NEZaY3BBNjZXOVU1MjRHUk5SUApzdXF6TEtXZjhiNjNKdnRkK09DNWNMd3NvdXIyaVB0aC8xM0pEVnVYMmhlWWRrcklGS1IwNzVNY2QrTERUaXRjCmhDdHoxMlBhTXlmSTRKUWsrUHJ3YUNCNzZzUGxzY1BtZU5xWGVQdXArd21jTTVUZ1g1NzYrWk9NVG1uVWxFZE0KVVFxNkxwQUJTS2h6dU5uZlRUMEc3SXNjVW1uMFhtZ0tCMTV1NGdydXBXRjFhcjVlRVplQUEzM0ZKOHZ5eGhkeApqd3hrNW9yOTNENm5DcjNMVGR1dDloeXVLTXdUOGJRNEw4MlhDTnNDQUJLMXlpYWQvNFUrb3hua2MzRnZoL2ZBCkQwNy84c2RjN2dvbkZrc3A3Nk8xVHhGNWxYU2x4RCtCeWpJZElkbEpxMFN6YkpjQjNUN3ExMmQ3b3J6YnNmdHIKV0RXV3RTMGpIY0hRbkVBek1URkI4eENST2gybzB5bnpaWkpQN3Q4RGYza1NjcTBpWmJieGN4UFVQSEhSNVhiYQpEY2kvenlxamVyTE5ObzRKdTEwaStwZzl4TmpDTTlnYktaOXNZYk1pM3pyWkZmbkxtUUtDQVFFQTJET0hvKzh6Cm5kUUFJczVud0ttbFV3Zng3ajVEK0hSdFpvWkdiY2FXYkQyT0tvVS8zL0hmYnVnSkRWSjQrcFkvUUY5TWRKT1YKa3ZwaGFQMFkzMC9mL3VYSlJtdUlyZUNEWnEzWnk4bXd3QlNxNjREK3h5dm1HcFI5cWZkT2hBNlo3cWVjTUtXUwoyRTZodFIwSjR5eUI3RkdHdktmcXBuWWVjME9Sc2hpbHpzUWR0RGFkS0NuU0lIaGtYT2NoVGEwNTE5UHB5NGtHCll2YmErdllLZEJUVHpUQVpWQTlDTWRZYVpITFJyZ2gxWVg2eEhlY2Nad1JmV1IwMWFSdFEvbFdjQ1p5b3pkQnEKQnJLU29meFl0cWNMSzhndHcrVmY5L1hQTHM3cCtDZVAyUzdLQ212VEVJV0pNdlA1czVNMEpQMzNiOHJIRktTSAp6VnI5Tmcwd1FTN1JlUUtDQVFFQThxWnpiMkdxd1Y5VU4zZjlZaGwxQ09talpzQ0wwNmdtMEQvOWxMdUpLSlFxClUrRzMydk84K3dSNHpHZmJLY3BPQ09MUzBWSEF2cnQwMUF6alZjMGoxeWxsRE5zM2FVbStLWENaY1RnenpxYUIKZ2ZkQS9mbXh3ZVhjQjBqdEczUzc4QmYvcGhqbmRUQkwySzRPYXRZTU45NEQvbkRHNlc4WnNmOWtTYmt0RXVGQQowNUhBLzBDSGhrNWV4OEFKMFhQRzhVNzZVYldub0M5VjFiUHJ1U1N0R2hxOHBnVHc5L2NtTnE5OXZTR0V3SXA3CjZ6UTBSN05Qb1ZpLzg5MG5jeC9rQ2gwZGRXbzhhVm9UY2NQYWE2S1JtMlA4NlhoNkt3NWRDcXhXcFlLYTdmU2gKMkJxWnZUa0tadnI5T002S0Fia2xCK3hqcXlXS3hZb0tXQmpiZXFMclZRS0NBUUVBa041bWd6aWpNNXg4d3RYZgp1Nzl4SWlQdXZwOUdXRk5iZ3hseVU5aC9ydVBJUVVHc1BWa0xTSHQrcFVpZisvbDFSS01XemY2ZWVUQUEyYUxPCmFjUlI2YkQ3bjQ0cXRhZjlKRzVWeERIUGw4WEJpYkNVQjgyb2tDTHoyVkgzY0pHQUgrUjd5alVJSXB6OXlpZzkKR2RZVzhNem9KYjIyZy9nZUMwbzVkRWNEdzNxeUZMR0x1UC9jNXhrRTF5T2dzelhoem5jVzcrVlBQRDBCR3F5Rwo4S1dNRHErdUtSOVlVYUNQYXNOdE1OcEdIU0FSZW1JRUxCdEg4S1NieDJRZ2Iydlo5SzdlaFpxamtQMVROK3VwClhpcXNWNWY0NG96dU0yNm9kMHI2aCtlcWdmTFNPdzFwRG1jTU9mSTFYVmpEMWcyL0lVK1Urb1lNNFZPWTNBRVcKVm5jU3NRS0NBUUFBODVnbVNxckJ3Vjd5TEwxSW9qTHNTd1pDQStWSWVqTlV3N3Q1MXRadDIwN2pMMUpxUUdSdwpVNDhwdGdxTSttY2Q3ODNGMWwwOElqNE9DdExsWmoyS3ZYWFEvQmNXaVp4K1N4dSs3dXA5Ri9nUUMya3MxY3JWCnFOSVpFVGNrMFd0ZlFLalcvT2dEZEtJSGduODUrZ2JvUFMyazFNcGk1ZldpMWc2Tm4zVkd5cTFYWnczcnNsUVYKdWI3elo1UmlSdUx6MVV4ei81TmR0SEhRdWJqbDYvZmx6MDhJRTZMaVJnelhVQTdkTEFGNlE5RENsbHpTSHlqagp5QlpRbllCbkdpdnB3ajE0VldkUlBuSXZFd2FMUDRMMHFncTIyNnNXK2lKeFJVVzl0bXBuSG50My9ucTEzRUJuCk1QckhPMEFkUzUyU2oySEFyUkFEUUV4VUZoemVPVDlWQW9JQkFGQjZMVk01SHZGcnFpaHNoaytJL1hjUEdCb0wKWUxUWTE2ZHl2MXczQ254eUh1MVBleElmZlNud2UwMFZzTXE3QzRIZGxJMzJ3ck1XckVQbVZUdG5LRGovN1RYQgo5bmc1L2xpN09xUWhheDN0R2VqZ1prQlNrWnFjTFdCWkJrUDNhbm5hS3dyWDgyZlVwNWRmMXNXUjV2T1V1czBOCk9LRnlUdWJhMy9YdGNpQ2UxRHhieGM2MWQyZk9iWE43T1NubTE3eS8yNG5UU2E5a2x2VVRudkVsa2tlSWR2OGMKT1NBTmtsY0pBOVJxMkhiMjFESC9UT2xsTXR0d0g3RUVBQW9ONkhiNWpWVkZZSmVnT2VQSm1TeEZTT1orS05naQo1MUo3VHorcXBRb0pkc1dKRUNUdFRuak5YdmhodDgyZTgyWkhYd0FPN1B3L0ZsT3V2cnU2TXh0RTA1VT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
  os:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBam00dldVb1cvMXZIeVZMVHNiQ0RHVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qVXhNakUwTVRZek16STVXaGNOTXpVeE1qRXlNVFl6TXpJNVdqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQVAzYlp6QW1rNWE1ckFkTGJEYStUaVc3eURicm03SVZJRGtrCmM2cU9PVFFubzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkZPV0l2SW1HZGp1Tk1QLwpwc2NvMTRCRjVMRnRNQVVHQXl0bGNBTkJBRUFvWUVEUmRNVmp2V3NXdW1xMGx2emtLckpFa1ZmYkZZdm01eGU5CmtNMnQzcW90Q0xYSGdkdWdkaEs0Y3Y4MEpCK3VvMWQ5SEVNZnBSUUM3elZaSWcwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJSnhoZ0NQL2kxa1dTY2l5ZnRJUGZVbUMwdnA4WVMwM244WkpMV1BEVVJiMQotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
`

	secretBundle, err := SecretBundleDecoder(yamlData)
	if err != nil {
		t.Fatalf("SecretBundleDecoder() error = %v", err)
	}

	if secretBundle.Cluster.ID != "YH3l-VgVZixkteeFT_sLGQL6xr3U00sA_VBkVTzoh5Q=" {
		t.Errorf("SecretBundleDecoder() Cluster.ID = %v, want %v", secretBundle.Cluster.ID, "YH3l-VgVZixkteeFT_sLGQL6xr3U00sA_VBkVTzoh5Q=")
	}

	if secretBundle.Secrets.BootstrapToken != "g4ywb6.g9g492ad01whv1s2" {
		t.Errorf("SecretBundleDecoder() Secrets.BootstrapToken = %v, want %v", secretBundle.Secrets.BootstrapToken, "g4ywb6.g9g492ad01whv1s2")
	}
}

func TestGenSans(t *testing.T) {
	name := "test-node"
	replicas := 3
	expected := []string{"test-node", "test-node-0", "test-node-1", "test-node-2"}

	got := GenSans(name, &replicas)
	if len(got) != len(expected) {
		t.Fatalf("GenSans() returned %d items, want %d", len(got), len(expected))
	}
	for i, s := range got {
		if s != expected[i] {
			t.Errorf("GenSans()[%d] = %v, want %v", i, s, expected[i])
		}
	}

	gotNil := GenSans(name, nil)
	if len(gotNil) != 1 || gotNil[0] != name {
		t.Errorf("GenSans() with nil replicas = %v, want [%v]", gotNil, name)
	}
}

func TestMarshalStringSlice(t *testing.T) {
	slice := []string{"one", "two", "three"}
	expected := `["one","two","three"]`

	got := MarshalStringSlice(slice)
	if got != expected {
		t.Errorf("MarshalStringSlice() = %v, want %v", got, expected)
	}
}

func TestPtrToString(t *testing.T) {
	s := "test"
	if got := PtrToString(&s); got != s {
		t.Errorf("PtrToString() = %v, want %v", got, s)
	}
	if got := PtrToString(nil); got != "" {
		t.Errorf("PtrToString(nil) = %v, want \"\"", got)
	}
}

func TestHasVersionSuffix(t *testing.T) {
	tests := []struct {
		input string
		want  bool
	}{
		{"image:v1.0.0", true},
		{"image:v1.2", true}, // Regex :v\d+(\.\d+)*$ matches v1.2
		{"image:v1", true},
		{"image:v1.2.3.4", true}, // Regex allows multiple components
		{"image:1.0.0", false},
		{"image", false},
		{"image:v1.2.3", true},
		{"image:1.0.0", false},
		{"image", false},
	}

	for _, tt := range tests {
		if got := HasVersionSuffix(tt.input); got != tt.want {
			t.Errorf("HasVersionSuffix(%q) = %v, want %v", tt.input, got, tt.want)
		}
	}
}

func TestIsValidTalosVersion(t *testing.T) {
	tests := []struct {
		input string
		want  bool
	}{
		{"v1.0.0", true},
		{"v1.2", true},
		{"v1", true},
		{"1.0.0", false},
		{"v1.0.0-beta", false},
	}
	// Re-reading IsValidTalosVersion regex: `^v\d+(\.\d+)*$`
	// It strictly matches vDigits(.Digits)*

	for _, tt := range tests {
		if got := IsValidTalosVersion(tt.input); got != tt.want {
			t.Errorf("IsValidTalosVersion(%q) = %v, want %v", tt.input, got, tt.want)
		}
	}
}

func TestStringToBytePtr(t *testing.T) {
	s := "test"
	ptr := StringToBytePtr(s)
	if ptr == nil {
		t.Fatal("StringToBytePtr() returned nil")
	}
	if string(*ptr) != s {
		t.Errorf("StringToBytePtr() content = %v, want %v", string(*ptr), s)
	}
}
