---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-talos-alperen-cloud-v1alpha1-taloscontrolplane
  failurePolicy: Fail
  name: vtaloscontrolplane-v1alpha1.kb.io
  rules:
  - apiGroups:
    - talos.alperen.cloud
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - taloscontrolplanes
  sideEffects: None
