# permissions for end users to edit talosworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: talos-operator
    app.kubernetes.io/managed-by: kustomize
  name: talosworker-editor-role
rules:
- apiGroups:
  - talos.alperen.cloud
  resources:
  - talosworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - talos.alperen.cloud
  resources:
  - talosworkers/status
  verbs:
  - get
