name: Enhancement Tracking Issue
description: Provide supporting details for a feature in development
title: "[Feature]: "
labels: ["feature"] 
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Please clearly describe the feature you would like to see added to TalosOperator.
        It might be either a new CRD, a new field to existing CRDs or an updated reconciliation logic for an existing CRD. 
        TalosOperator is well designed to be extensible and flexible but make sure that what you had requested is feasible and exists in Talos API.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true