apiVersion: talos.alperen.cloud/v1alpha1
kind: TalosControlPlane
metadata:
  labels:
    app.kubernetes.io/name: talos-operator
    app.kubernetes.io/managed-by: kustomize
  name: taloscontrolplane-sample
spec:
  version: v1.10.3
  mode: container 
  replicas: 2
  kubeVersion: v1.33.0

  podCIDR: 
  - 10.100.0.0/16
  - 10.150.0.0/16
  serviceCIDR:
  - 10.200.0.0/12
#  configRef: 
#    name: taloscontrolplane-sample-config
#    key: controlplane.yaml