apiVersion: talos.alperen.cloud/v1alpha1
kind: TalosClusterAddon
metadata:
  labels:
    app.kubernetes.io/name: talos-operator
    app.kubernetes.io/managed-by: kustomize
  name: talosclusteraddon-sample
spec:
  clusterSelector:
    matchLabels:
      zort: hort
  helmSpec: 
    repoURL: https://metallb.github.io/metallb
    chartName: metallb
    releaseName: metallb
