apiVersion: talos.alperen.cloud/v1alpha1
kind: TalosAddon
metadata:
  name: cert-manager
  namespace: default
spec:
  clusterRef:
    name: my-talos-cluster
  
  helmRelease:
    chartName: cert-manager
    repoURL: https://charts.jetstack.io
    version: "v1.13.0"
    releaseName: cert-manager
    targetNamespace: cert-manager
    
    # Example of using valuesFrom to reference a ConfigMap
    valuesFrom:
      - kind: ConfigMap
        name: cert-manager-values
        # Optional: specify a key to use only that key's value
        # key: values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-values
  namespace: default
data:
  installCRDs: "true"
  global.leaderElection.namespace: "cert-manager"
