apiVersion: talos.alperen.cloud/v1alpha1
kind: TalosWorker
metadata:
  name: talosworker-sample
spec:
  version: v1.12.1
  mode: container
  replicas: 2
  kubeVersion: v1.35.0
  controlPlaneRef:
    name: taloscontrolplane-sample