{{- if .Values.featureFlags.enablePxeBootStack }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: matchbox-assets-pv
spec:
  claimRef:
    name: matchbox-assets-pvc
    namespace: "{{ .Release.Namespace }}"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "{{ .Values.pxeBootStack.matchbox.assetsPvPath }}"
{{- end }}
