apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "talos-operator.fullname" . }}  
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - talos.alperen.cloud
  resources:
  - talosclusters
  - taloscontrolplanes
  - talosmachines
  - talosworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - talos.alperen.cloud
  resources:
  - talosclusters/finalizers
  - taloscontrolplanes/finalizers
  - talosmachines/finalizers
  - talosworkers/finalizers
  verbs:
  - update
- apiGroups:
  - talos.alperen.cloud
  resources:
  - talosclusters/status
  - taloscontrolplanes/status
  - talosmachines/status
  - talosworkers/status
  verbs:
  - get
  - patch
  - update