bind-interfaces

# Disable DNS
port=0

# TFTP server:
enable-tftp
tftp-root=/var/lib/tftp

# UEFI iPXE boot file:
dhcp-match=set:efi,option:client-arch,7
dhcp-boot=tag:efi,ipxe.efi

# Tagging iPXE clients:
dhcp-userclass=set:ipxe,iPXE

{{ range . }}
# {{ .Name }}
tag-if=set:if_{{ .PxeInterface }},tag:{{ .PxeInterface }}
dhcp-range=tag:if_{{ .PxeInterface }},{{ .PxeIpAddress }},static
dhcp-boot=tag:if_{{ .PxeInterface }},tag:ipxe,http://{{ .PxeIpAddress }}:{{ .MatchboxPort }}/boot.ipxe
{{ $PxeInterface := .PxeInterface }}
{{- range .Machines }}
dhcp-host=tag:if_{{ $PxeInterface }},{{ .MacAddress }},{{ .IpAddress }}
{{- end }}
{{- end }}