bind-interfaces

# Disable DNS
port=0

# TFTP server:
enable-tftp
tftp-root=/var/lib/tftp

# iPXE boot file:
# For x86_64 EFI:
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:efi-x86_64,ipxe-efi-x86_64.efi
# For arm64 EFI:
dhcp-match=set:efi-arm64,option:client-arch,11
dhcp-boot=tag:efi-arm64,ipxe-efi-arm64.efi

# Tagging iPXE clients:
dhcp-userclass=set:ipxe,iPXE

{{ range . }}
# {{ .Name }}
tag-if=set:if_{{ .PxeInterface }},tag:{{ .PxeInterface }}
dhcp-range=tag:if_{{ .PxeInterface }},{{ .PxeIpAddress }},static
dhcp-boot=tag:if_{{ .PxeInterface }},tag:ipxe,http://{{ .PxeIpAddress }}:{{ .MatchboxPort }}/boot.ipxe
{{ $PxeInterface := .PxeInterface }}
{{- range .Machines }}
dhcp-host=tag:if_{{ $PxeInterface }},{{ .MacAddress }},{{ .IpAddress }}
{{- end }}
{{- end }}