name: Release

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'
      - 'hack/**'

jobs:
  release:
    permissions:
      packages: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24

      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set environment variables
        run: |
          echo "BUILD_IMAGE=golang:1.24" >> $GITHUB_ENV
          echo "KO_DOCKER_REPO=alperencelik/talos-operator" >> $GITHUB_ENV
        
      - name: Run mage.go Release
        run: go run mage.go Release
        env: 
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build-ui-image:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ui 
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            alperencelik/talos-operator-ui:${{ github.ref_name }}
            alperencelik/talos-operator-ui:latest